service: archiveData

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  timeout: 300

functions:
  dataHandler:
    handler: handler.handler
    events:
      - schedule: cron(15 1 * * ? *)
