service: archiveGDOT

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  timeout: 300

functions:
  cronHandler:
    handler: handler.handler
    events:
      # Invoke Lambda function every day at 1am
      - schedule: rate(30 days)
