service: cityLegisProxy

frameworkVersion: '2 || 3'


provider:
  name: aws
  iam:
    role: arn:aws:iam::882020251952:role/service-role/liquidbibleParse-role-njpagsyx
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 29
  httpApi:
    cors: true

functions:
  proxy:
    handler: handler.handler
    events:
      - httpApi:
          method: GET
          path: /{proxy+}
