service: summarize911

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  timeout: 300

functions:
  cronHandler:
    handler: handler.handler
    events:
      - schedule: cron(0 2 * * ? *)
